# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.1.3"

default_platform :ios

platform :ios do
  desc "Build for Simulator"
  lane :build_simulator do |options|
    xcodebuild(
      project: "PrettyStore.xcodeproj",
      scheme: "PrettyStore",
      configuration: "Release",
      clean: true,
      build: true,
      derivedDataPath: "./build",
      archivePath: "./build/Products/PrettyStore.xcarchive",
      sdk: "iphonesimulator",
      build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      }
    )
  end
end
